### ISSUE TITLE
Installation instructions DO NOT WORK

### ISSUE THREAD

**Issue by Black6spdZ** [strollo/altf_theme#2]
cd /usr/www/scripts
$ git clone https://github.com/strollo/altf_theme.git modern
-sh: **git: not found**

**Comment by strollo** [comment]
@Black6spdZ git is, roughly speaking, a program for versioning that is here used to retrieve sources from github.
It must be manually installed by you before executing all the other instructions.
You can so find it in the list of installable packages then install it, so proceed.
